version: '3.8'

services:
  backup:
    build:
      context: ./backup/
    restart: unless-stopped
    volumes:
      - ./borgdir/cache:/root/.cache/borg # this is where the local borg cache resides
      - ./borgdir/repo:/borgdir # this is where the local borg repo resides
      # both of these preceeding entries must persist from run to run - see borg docs for the repo and cache for more info

      # example configuration
      # - /path/to/backup:/backups/backupTitle:ro
      # - /path/to/rclone.conf:/rclone.conf:ro
    environment:
      - TZ=America/Chicago
      - BACKUP_TITLE=My_Stuff
      - RCLONE_REMOTE_NAME=MyRemote
      # dir with no trailing slash
      - RCLONE_REMOTE_BACKUP_PATH=bucket/then/path
      # - BACKUP_15MIN=true
      # - BACKUP_HOURLY=true
      - BACKUP_DAILY=true
      # - BACKUP_WEEKLY=true
      # - BACKUP_MONTHLY=true
      # - RCLONE_S3_ACCESS_KEY_ID
      # - RCLONE_S3_SECRET_ACCESS_KEY
      - RCLONE_S3_ACCESS_KEY_ID_FILE=/run/secrets/borg_s3_key
      - RCLONE_S3_SECRET_ACCESS_KEY_FILE=/run/secrets/borg_s3_secret
      - BORG_PASSPHRASE_FILE=/run/secrets/borg_encryption_passphrase
      - RUN_ON_START=true
      # see https://borgbackup.readthedocs.io/en/stable/usage/prune.html
      - PRUNE_KEEP_HOURLY_COUNT=24
      - PRUNE_KEEP_DAILY_COUNT=21
      - PRUNE_KEEP_WEEKLY_COUNT=5
      - PRUNE_KEEP_MONTHLY_COUNT=1
      # - PRUNE_KEEP_YEARLY_COUNT=0
      # - PRUNE_KEEP_ALL_WITHIN=48H
      # - PRUNE_GLOB=My_Stuff*
    secrets:
      - borg_s3_key
      - borg_s3_secret
      - borg_encryption_passphrase

secrets:
  borg_s3_key:
    external: true
  borg_s3_secret:
    external: true
  borg_encryption_passphrase:
    external: true
